export default [
  {
    id: "set-pieces-1",
    kw: require("../../../../../assets/img/pieces/default/kw.png"),
    qw: require("../../../../../assets/img/pieces/default/qw.png"),
    rw: require("../../../../../assets/img/pieces/default/rw.png"),
    bw: require("../../../../../assets/img/pieces/default/bw.png"),
    nw: require("../../../../../assets/img/pieces/default/nw.png"),
    pw: require("../../../../../assets/img/pieces/default/pw.png"),

    kb: require("../../../../../assets/img/pieces/default/kb.png"),
    qb: require("../../../../../assets/img/pieces/default/qb.png"),
    rb: require("../../../../../assets/img/pieces/default/rb.png"),
    bb: require("../../../../../assets/img/pieces/default/bb.png"),
    nb: require("../../../../../assets/img/pieces/default/nb.png"),
    pb: require("../../../../../assets/img/pieces/default/pb.png"),
  },
  {
    id: "set-pieces-2",
    kw: require("../../../../../assets/img/pieces/set-2/kw.png"),
    qw: require("../../../../../assets/img/pieces/set-2/qw.png"),
    rw: require("../../../../../assets/img/pieces/set-2/rw.png"),
    bw: require("../../../../../assets/img/pieces/set-2/bw.png"),
    nw: require("../../../../../assets/img/pieces/set-2/nw.png"),
    pw: require("../../../../../assets/img/pieces/set-2/pw.png"),

    kb: require("../../../../../assets/img/pieces/set-2/kb.png"),
    qb: require("../../../../../assets/img/pieces/set-2/qb.png"),
    rb: require("../../../../../assets/img/pieces/set-2/rb.png"),
    bb: require("../../../../../assets/img/pieces/set-2/bb.png"),
    nb: require("../../../../../assets/img/pieces/set-2/nb.png"),
    pb: require("../../../../../assets/img/pieces/set-2/pb.png"),
  },
  {
    id: "set-pieces-3",
    kw: require("../../../../../assets/img/pieces/set-3/kw.png"),
    qw: require("../../../../../assets/img/pieces/set-3/qw.png"),
    rw: require("../../../../../assets/img/pieces/set-3/rw.png"),
    bw: require("../../../../../assets/img/pieces/set-3/bw.png"),
    nw: require("../../../../../assets/img/pieces/set-3/nw.png"),
    pw: require("../../../../../assets/img/pieces/set-3/pw.png"),

    kb: require("../../../../../assets/img/pieces/set-3/kb.png"),
    qb: require("../../../../../assets/img/pieces/set-3/qb.png"),
    rb: require("../../../../../assets/img/pieces/set-3/rb.png"),
    bb: require("../../../../../assets/img/pieces/set-3/bb.png"),
    nb: require("../../../../../assets/img/pieces/set-3/nb.png"),
    pb: require("../../../../../assets/img/pieces/set-3/pb.png"),
  },
];
