export default [
  {
    title: "Bases",
    titleColor: "white",
    whiteCell: "#F0D9B5",
    blackCell: "#B58863",
    borderCell: false,
    id: "Bases",
    background: require("../../../../img/backgrounds/themes/bases.jpg"),
  },
  {
    title: "Harry Potter",
    titleColor: "white",
    whiteCell: "#d4d4d4",
    blackCell: "#23597d",
    borderCell: "gray",
    id: "Harry Potter",
    background: require("../../../../img/backgrounds/themes/harry-potter.jpg"),
  },
  {
    title: "The Queen's Gambit",
    titleColor: "white",
    whiteCell: "#bcbdaf",
    blackCell: "#9c3232",
    borderCell: false,
    id: "Queens Gambit",
    background: require("../../../../img/backgrounds/themes/queens-gambit.jpg"),
  },
  {
    title: "Forest",
    titleColor: "white",
    whiteCell: "#ccc99f",
    blackCell: "#259c2d",
    borderCell: "#996d40",
    id: "Forest",
    background: require("../../../../img/backgrounds/themes/forest.jpg"),
  },
  {
    title: "Sky",
    titleColor: "gray",
    whiteCell: "#f7f7f7",
    blackCell: "#a3e0f7",
    borderCell: "gray",
    id: "Sky",
    background: require("../../../../img/backgrounds/themes/sky.jpg"),
  },
  {
    title: "Bubblegums",
    titleColor: "white",
    whiteCell: "#ffe0ee",
    blackCell: "#ff85bc",
    borderCell: false,
    id: "Bubblegums",
    background: require("../../../../img/backgrounds/themes/bubblegums.jpg"),
  },
  {
    title: "Steel",
    titleColor: "white",
    whiteCell: "#f2f2f2",
    blackCell: "#c7c7c7",
    borderCell: false,
    id: "Steel",
    background: require("../../../../img/backgrounds/themes/steel.jpg"),
  },
];
